import { ivl, transpose, type Interval } from './interval';
import { formatPitch, parseNote, pitchClass, type Note } from './note';

/**
 * Keys and scales.
 *
 * Scales are generated by stacking spelled intervals from the tonic, never by
 * picking semitones off a chromatic list. That is why G♭ major comes out with a
 * C♭ in it rather than a B, and why B major gets an A♯ rather than a B♭ — the
 * fourth degree of G♭ *is* a kind of C, and the spelling follows from that.
 */

export type Mode =
	| 'ionian'
	| 'dorian'
	| 'phrygian'
	| 'lydian'
	| 'mixolydian'
	| 'aeolian'
	| 'locrian'
	| 'harmonicMinor'
	| 'melodicMinor';

export type Key = { tonic: Note; mode: Mode };

/** Interval pattern of each mode, as names, from the tonic. */
const MODE_INTERVALS: Record<Mode, string[]> = {
	lydian: ['P1', 'M2', 'M3', 'A4', 'P5', 'M6', 'M7'],
	ionian: ['P1', 'M2', 'M3', 'P4', 'P5', 'M6', 'M7'],
	mixolydian: ['P1', 'M2', 'M3', 'P4', 'P5', 'M6', 'm7'],
	dorian: ['P1', 'M2', 'm3', 'P4', 'P5', 'M6', 'm7'],
	aeolian: ['P1', 'M2', 'm3', 'P4', 'P5', 'm6', 'm7'],
	phrygian: ['P1', 'm2', 'm3', 'P4', 'P5', 'm6', 'm7'],
	locrian: ['P1', 'm2', 'm3', 'P4', 'd5', 'm6', 'm7'],
	harmonicMinor: ['P1', 'M2', 'm3', 'P4', 'P5', 'm6', 'M7'],
	melodicMinor: ['P1', 'M2', 'm3', 'P4', 'P5', 'M6', 'M7']
};

/**
 * Brightest to darkest. This is the axis the wheel renders as a clockwise arc:
 * each step down flattens exactly one more degree.
 */
export const BRIGHTNESS_ORDER: Mode[] = [
	'lydian',
	'ionian',
	'mixolydian',
	'dorian',
	'aeolian',
	'phrygian',
	'locrian'
];

export const MAJOR: Mode = 'ionian';
export const MINOR: Mode = 'aeolian';

export function key(tonic: Note | string, mode: Mode = 'ionian'): Key {
	return { tonic: typeof tonic === 'string' ? parseNote(tonic) : tonic, mode };
}

export function scaleIntervals(mode: Mode): Interval[] {
	return MODE_INTERVALS[mode].map(ivl);
}

/** The seven spelled notes of a key, starting on the tonic. */
export function scale(k: Key): Note[] {
	return scaleIntervals(k.mode).map((interval) => transpose(k.tonic, interval));
}

/** Scale degree 1–7 as a spelled note. */
export function degree(k: Key, n: number): Note {
	if (n < 1 || n > 7) throw new Error(`Scale degree out of range: ${n}`);
	return scale(k)[n - 1];
}

/**
 * Key signature as a signed count: positive is sharps, negative is flats.
 * Derived by summing the alterations in the scale, so it works for every mode
 * rather than only for major and minor.
 */
export function keySignature(k: Key): number {
	return scale(k).reduce((total, n) => total + n.alter, 0);
}

/** True when the key writes its accidentals as flats. */
export function prefersFlats(k: Key): boolean {
	const signature = keySignature(k);
	// C major and A minor have no accidentals; jazz spells their chromatic notes
	// as flats far more often than sharps (Eb, Ab, Bb over D#, G#, A#).
	return signature <= 0;
}

/** Position on the circle of fifths, C = 0, moving clockwise by fifths. */
export function circleOfFifthsIndex(pc: number): number {
	return (((pc * 7) % 12) + 12) % 12;
}

/**
 * Shortest distance between two keys measured in fifths, 0–6.
 * This is the number the wheel draws as an arc, and the number the curriculum
 * uses to order modulations by difficulty.
 */
export function fifthsDistance(a: Key, b: Key): number {
	const from = circleOfFifthsIndex(pitchClass(a.tonic));
	const to = circleOfFifthsIndex(pitchClass(b.tonic));
	const raw = (((to - from) % 12) + 12) % 12;
	return Math.min(raw, 12 - raw);
}

/** Pitch classes of a key's scale, for fast membership tests. */
export function scalePitchClasses(k: Key): Set<number> {
	return new Set(scale(k).map(pitchClass));
}

export function isDiatonic(k: Key, pc: number): boolean {
	return scalePitchClasses(k).has(pc);
}

export function formatKey(k: Key, unicode = false): string {
	const tonic = formatPitch(k.tonic, unicode);
	if (k.mode === 'ionian') return tonic;
	if (k.mode === 'aeolian') return `${tonic}m`;
	if (k.mode === 'harmonicMinor') return `${tonic}m (harmonic)`;
	if (k.mode === 'melodicMinor') return `${tonic}m (melodic)`;
	return `${tonic} ${k.mode}`;
}

/**
 * Parse `C`, `Ebm`, `F# dorian`. Minor is written with a trailing `m`, matching
 * how key centres are stored in the database.
 */
export function parseKey(text: string): Key {
	const trimmed = text.trim();
	const spaced = trimmed.match(/^(\S+)\s+(\w+)$/);
	if (spaced) {
		// Match case-insensitively without lowercasing the result: the mode keys
		// are a mix of lowercase ('dorian') and camelCase ('harmonicMinor').
		const wanted = spaced[2].toLowerCase();
		const mode = (Object.keys(MODE_INTERVALS) as Mode[]).find((m) => m.toLowerCase() === wanted);
		if (!mode) throw new Error(`Unknown mode: ${spaced[2]}`);
		return { tonic: parseNote(spaced[1]), mode };
	}
	if (/m$/.test(trimmed) && !/^[A-Ga-g](bb|##|[b#♭♯])?$/.test(trimmed)) {
		return { tonic: parseNote(trimmed.slice(0, -1)), mode: 'aeolian' };
	}
	return { tonic: parseNote(trimmed), mode: 'ionian' };
}

/** The relative major of a minor key, and vice versa. */
export function relativeKey(k: Key): Key {
	if (k.mode === 'ionian') return { tonic: transpose(k.tonic, ivl('M6')), mode: 'aeolian' };
	if (k.mode === 'aeolian') return { tonic: transpose(k.tonic, ivl('m3')), mode: 'ionian' };
	throw new Error(`No relative key defined for ${k.mode}`);
}

export function parallelKey(k: Key): Key {
	if (k.mode === 'ionian') return { tonic: k.tonic, mode: 'aeolian' };
	if (k.mode === 'aeolian') return { tonic: k.tonic, mode: 'ionian' };
	throw new Error(`No parallel key defined for ${k.mode}`);
}
