import { describe, expect, it } from 'vitest';
import type { CardPayload } from '$lib/curriculum/cards';
import { RUNGS, STAGES, itemsForRung } from '$lib/curriculum/ladder';
import { cardsForPivots, cardsForProgression, cardsForRung } from '$lib/curriculum/cards';
import { progressionById } from '$lib/curriculum/progressions';
import {
	choicesFor,
	diatonicNames,
	markGathered,
	markNamed,
	markPassage,
	markPlayed,
	markShape,
	materialOf,
	nameNeighbours,
	pose,
	shapeChoices,
	toVoicing
} from './drill';
import { vocabularyFromRungs, type Shape } from '$lib/curriculum/vocabulary';

const cmaj7: CardPayload = {
	kind: 'chord',
	label: 'Cmaj7',
	answerPitchClasses: [0, 4, 7, 11],
	answerVoicing: [48, 52, 55, 59],
	degree: 'I'
};

describe('posing a question', () => {
	it('says nothing on screen when the question is aural', () => {
		for (const direction of ['hear_name', 'hear_play'] as const) {
			const prompt = pose(direction, cmaj7);
			expect(prompt.visible, direction).toBeNull();
			expect(prompt.audible, direction).toEqual([48, 52, 55, 59]);
		}
	});

	it('shows the chord and stays silent when the answer is to play it', () => {
		const prompt = pose('see_play', cmaj7);
		expect(prompt.visible).toBe('Cmaj7');
		expect(prompt.audible).toBeNull();
		expect(prompt.answerWith).toBe('play');
	});

	it('asks for a name when naming is the point', () => {
		expect(pose('hear_name', cmaj7).answerWith).toBe('name');
		expect(pose('degree_play', cmaj7).answerWith).toBe('name');
	});

	it('still poses a retired direction rather than throwing on an old card', () => {
		// `play_name` is generated by nothing and queued by nothing, but rows that
		// carry it are still sitting in banks. Posing must be total over the enum.
		expect(pose('play_name', cmaj7).instruction.length).toBeGreaterThan(5);
	});

	it('never leaves you without an instruction', () => {
		for (const direction of [
			'hear_name',
			'hear_play',
			'see_play',
			'play_name',
			'degree_play'
		] as const) {
			expect(pose(direction, cmaj7).instruction.length, direction).toBeGreaterThan(5);
		}
	});

	it('asks for a degree by its numeral rather than by its symbol', () => {
		const prompt = pose('degree_play', cmaj7, 60, 'C');
		expect(prompt.visible).toBe('I — C');
		expect(prompt.visible).not.toContain('Cmaj7');
		expect(prompt.audible).toBeNull();
	});

	it('carries the key in the degree question, because a numeral alone is not one', () => {
		const four: CardPayload = {
			kind: 'triad',
			label: 'Ab',
			answerPitchClasses: [8, 0, 3],
			degree: 'IV'
		};
		expect(pose('degree_play', four, 60, 'Eb').visible).toBe('IV — E♭');
	});

	it('counts a relative minor’s numerals from the minor, not from the stage it is filed under', () => {
		// The A minor triads are stored on the C stage, so the card's own key says
		// C and the numeral means A minor. "i — C" would be a wrong question with
		// the right answer sitting behind it.
		const [, tonic] = itemsForRung('relative-minor', STAGES[0]);
		const prompt = pose('degree_play', { ...tonic, degree: tonic.degree! }, 60, 'C');
		expect(prompt.visible).toBe('i — Am');
	});

	it('ends the degree question on the name, the way play-then-name always has', () => {
		expect(pose('degree_play', cmaj7, 60, 'C').answerWith).toBe('name');
		expect(pose('degree_play', cmaj7, 60, 'C').instruction).toContain('name');
	});

	it('never writes the answer on a question that asks for the answer', () => {
		/*
		 * The rule the wheel reads, checked against everything the ladder makes.
		 *
		 * The wheel used to draw a card's notes whenever the prompt had anything
		 * written on it at all, which is true of `see_play` — where the chord's name
		 * *is* the prompt and lighting its notes tells you nothing new — and equally
		 * true of `degree_play`, where what is written is `vi — C` and the notes are
		 * the whole question. The honest test is not whether a question says
		 * something but whether it says *this*, so that is what the wheel asks now
		 * and this is what keeps it answerable.
		 */
		for (const stage of STAGES) {
			for (const rung of RUNGS) {
				for (const card of cardsForRung(rung.id, stage)) {
					const prompt = pose(card.direction, card.payload, 60, card.keyCenter);
					if (prompt.answerWith !== 'name') continue;
					expect(prompt.visible, `${stage.key}/${rung.id}/${card.direction}`).not.toBe(
						card.payload.label
					);
				}
			}
		}
	});

	it('builds a voicing when the card does not carry one', () => {
		const bare: CardPayload = { kind: 'chord', label: 'Dm', answerPitchClasses: [2, 5, 9] };
		const prompt = pose('hear_play', bare);
		expect(prompt.audible).toHaveLength(3);
		expect(prompt.audible!.every((n) => n >= 60 && n < 84)).toBe(true);
	});

	it('plays a scale continuously through the tonic in the next octave', () => {
		const scale: CardPayload = {
			kind: 'scale',
			label: 'D scale',
			answerPitchClasses: [2, 4, 6, 7, 9, 11, 1],
			answerVoicing: [62, 64, 66, 67, 69, 71, 61]
		};
		expect(pose('hear_play', scale).audible).toEqual([62, 64, 66, 67, 69, 71, 73, 74]);
	});
});

describe('turning the corner', () => {
	const pivot = cardsForPivots('C').find((card) => card.identity.includes('|G|'))!;
	const prompt = pose('pivot_play', pivot.payload, 60, 'C');

	/*
	 * The one crossing question with something written down — and what is written
	 * is two numerals rather than a chord, because the realisation that they point
	 * at the same place is the exercise.
	 */
	it('shows the two functions and withholds the chord', () => {
		expect(prompt.visible).toBe('Imaj7 in C · IVmaj7 in G');
		expect(prompt.visible).not.toContain('Cmaj7');
	});

	it('sounds nothing: this one is for the hands', () => {
		expect(prompt.audible).toBeNull();
	});

	it('is answered by playing the chord both numerals name', () => {
		expect(prompt.answerWith).toBe('play');
		expect(markPlayed(pivot.payload.answerPitchClasses, [60, 64, 67, 71]).correct).toBe(true);
		expect(markPlayed(pivot.payload.answerPitchClasses, [60, 64, 67]).correct).toBe(false);
	});
});

/*
 * The bug these exist for, in one sentence: a progression card's
 * `answerPitchClasses` is the union of every chord in it, and both of its
 * directions posed that union as a single chord — sounded as one cluster on
 * `hear_play`, and marked against all of it at once on both. Nobody
 * met it often, because progression cards only exist for a progression somebody
 * has pinned, but no ii–V–I card has ever been answerable.
 */
describe('a progression is a movement, not a chord', () => {
	const jazzCadence = progressionById('ii-V-I')!;
	const [onSight, byEar] = cardsForProgression(jazzCadence, 'C');
	const chords = [
		[2, 5, 9, 0],
		[7, 11, 2, 5],
		[0, 4, 7, 11]
	];

	it('hands the chords over in order rather than as one heap', () => {
		for (const card of [onSight, byEar]) {
			const prompt = pose(card.direction, card.payload, 60, card.keyCenter);
			expect(prompt.sequence, card.direction).not.toBeNull();
			expect(
				prompt.sequence!.map((step) => step.pitchClasses),
				card.direction
			).toEqual(chords);
		}
	});

	it('never sounds the whole progression as one chord', () => {
		const prompt = pose('hear_play', byEar.payload, 60, 'C');
		expect(prompt.audible).toBeNull();
		// The union it used to sound: seven pitch classes — the whole C major scale,
		// which is neither a chord nor a hand.
		expect(byEar.payload.answerPitchClasses).toHaveLength(7);
		expect(prompt.sequence!.every((step) => step.pitchClasses.length === 4)).toBe(true);
	});

	it('shows the numerals on sight and stays silent, because the spelling is the question', () => {
		const prompt = pose('see_play', onSight.payload, 60, 'C');
		expect(prompt.visible).toBe('ii7 – V7 – Imaj7');
		expect(prompt.audible).toBeNull();
		expect(prompt.answerWith).toBe('play');
		// Silent, but still a passage: it is answered chord by chord either way.
		expect(prompt.sequence).toHaveLength(3);
	});

	it('carries what each chord is called as well as what it does', () => {
		const prompt = pose('hear_play', byEar.payload, 60, 'C');
		expect(prompt.sequence!.map((step) => step.numeral)).toEqual(['ii7', 'V7', 'Imaj7']);
		expect(prompt.sequence!.map((step) => step.symbol)).toEqual(['Dm7', 'G7', 'Cmaj7']);
	});

	it('gives every chord something playable to sound', () => {
		const prompt = pose('hear_play', byEar.payload, 60, 'C');
		for (const step of prompt.sequence!) {
			expect(step.voicing).toHaveLength(4);
			expect(step.voicing.map((n) => ((n % 12) + 12) % 12).sort()).toEqual(
				[...step.pitchClasses].sort()
			);
		}
	});

	/*
	 * Cards are written once and never rewritten, so a row from before the steps
	 * were stored has to pose as something. It falls back to the old question,
	 * which is a poor one rather than a crash.
	 */
	it('falls back to the old single chord for a payload with no steps', () => {
		const stepless = { ...byEar.payload, steps: undefined };
		const prompt = pose('hear_play', stepless, 60, 'C');
		expect(prompt.sequence).toBeNull();
		expect(prompt.audible).not.toBeNull();
	});

	it('leaves every other question alone', () => {
		for (const direction of [
			'hear_name',
			'hear_play',
			'see_play',
			'play_name',
			'degree_play',
			'pivot_play'
		] as const) {
			expect(pose(direction, cmaj7, 60, 'C').sequence, direction).toBeNull();
		}
	});
});

/*
 * The keyboard window is cut from this rather than from the prompt, and the
 * whole point is that it does not go quiet when the question does.
 */
describe('what a card is made of', () => {
	it('gives a scale its whole octave, in the octave it was written in', () => {
		for (const stage of STAGES) {
			const [item] = itemsForRung('scale', stage);
			const payload = {
				kind: 'scale',
				label: item.label,
				answerPitchClasses: item.answerPitchClasses,
				answerVoicing: item.answerVoicing
			} as CardPayload;

			const notes = materialOf(payload, 60);
			expect(notes, item.label).toHaveLength(8);
			expect(notes[notes.length - 1] - notes[0], item.label).toBe(12);
			for (let i = 1; i < notes.length; i++) {
				expect(notes[i], item.label).toBeGreaterThan(notes[i - 1]);
			}
		}
	});

	/*
	 * `see_play` prints the scale's name and plays nothing, which is the whole of
	 * the question — and left everything reading `prompt.audible` with nothing to
	 * draw. Seven of the twelve scales then climbed off the right-hand end of a
	 * keyboard that had fallen back to C3–E5.
	 */
	it('says the same thing whether or not the question sounds it', () => {
		const [item] = itemsForRung(
			'scale',
			STAGES.find((s) => s.key === 'B')!
		);
		const payload = {
			kind: 'scale',
			label: item.label,
			answerPitchClasses: item.answerPitchClasses,
			answerVoicing: item.answerVoicing
		} as CardPayload;

		expect(pose('see_play', payload, 60).audible).toBeNull();
		expect(materialOf(payload, 60)).toEqual(pose('hear_play', payload, 60).audible);
	});

	it('gives a progression every chord of it rather than the union', () => {
		const [, byEar] = cardsForProgression(progressionById('ii-V-I')!, 'C');
		const notes = materialOf(byEar.payload, 60);
		expect(notes).toHaveLength(12);
		// The union is seven pitch classes — the whole key, and not a range.
		expect(byEar.payload.answerPitchClasses).toHaveLength(7);
	});

	it('gives a chord its stored voicing', () => {
		expect(materialOf(cmaj7, 60)).toEqual([48, 52, 55, 59]);
	});

	it('spreads a chord that never had one', () => {
		const { answerVoicing: _dropped, ...bare } = cmaj7;
		expect(materialOf(bare as CardPayload, 60)).toEqual([60, 64, 67, 71]);
	});
});

describe('spreading pitch classes into a voicing', () => {
	it('ascends', () => {
		const voicing = toVoicing([0, 4, 7, 11], 60);
		expect(voicing).toEqual([60, 64, 67, 71]);
		expect([...voicing].sort((a, b) => a - b)).toEqual(voicing);
	});

	it('wraps upward rather than descending', () => {
		const voicing = toVoicing([7, 11, 2, 5], 60);
		expect([...voicing].sort((a, b) => a - b)).toEqual(voicing);
	});

	it('keeps the pitch classes it was given', () => {
		const pcs = [2, 5, 9, 0];
		expect(toVoicing(pcs, 55).map((n) => n % 12)).toEqual(pcs);
	});
});

describe('marking a played answer', () => {
	it('accepts the right notes', () => {
		expect(markPlayed([60, 64, 67, 71], [60, 64, 67, 71]).correct).toBe(true);
	});

	it('accepts the right chord in another octave', () => {
		// Which octave you chose is a voicing question, asked separately.
		expect(markPlayed([60, 64, 67, 71], [48, 52, 55, 59]).correct).toBe(true);
	});

	it('accepts a doubled note', () => {
		expect(markPlayed([60, 64, 67], [60, 64, 67, 72]).correct).toBe(true);
	});

	it('accepts any inversion', () => {
		expect(markPlayed([60, 64, 67, 71], [64, 67, 71, 72]).correct).toBe(true);
	});

	it('reports what was missing', () => {
		const marking = markPlayed([60, 64, 67, 71], [60, 64, 67]);
		expect(marking.correct).toBe(false);
		expect(marking.missing).toEqual([11]);
		expect(marking.extra).toEqual([]);
	});

	it('reports what was extra', () => {
		const marking = markPlayed([60, 64, 67], [60, 64, 67, 70]);
		expect(marking.correct).toBe(false);
		expect(marking.extra).toEqual([10]);
	});

	it('fails an empty answer', () => {
		expect(markPlayed([60, 64, 67], []).correct).toBe(false);
	});
});

describe('marking something played over time', () => {
	const C_MAJOR = [0, 2, 4, 5, 7, 9, 11];

	it('accepts a scale played one note at a time', () => {
		// The bug this exists to prevent: comparing a scale as a chord demanded
		// all seven notes simultaneously, which nobody can play.
		expect(markGathered(C_MAJOR, [60, 62, 64, 65, 67, 69, 71]).correct).toBe(true);
	});

	it('accepts it in any octave and any order', () => {
		expect(markGathered(C_MAJOR, [71, 48, 62, 76, 65, 57, 55]).correct).toBe(true);
	});

	it('reports which notes are still needed, by pitch class', () => {
		const marking = markGathered(C_MAJOR, [60, 64, 67]);
		expect(marking.correct).toBe(false);
		expect(marking.missing).toEqual([2, 5, 9, 11]);
	});

	it('forgives repeats and passing notes', () => {
		// Scales get played with repeats and stray notes; that is not an error.
		const marking = markGathered(C_MAJOR, [60, 60, 62, 63, 64, 65, 67, 69, 71]);
		expect(marking.correct).toBe(true);
		expect(marking.extra).toEqual([]);
	});

	it('is not satisfied by nothing', () => {
		expect(markGathered(C_MAJOR, []).correct).toBe(false);
		expect(markGathered(C_MAJOR, []).missing).toHaveLength(7);
	});

	it('completes as the last note arrives', () => {
		let gathered: number[] = [];
		const order = [60, 62, 64, 65, 67, 69, 71];
		const results = order.map((note) => {
			gathered = [...gathered, note];
			return markGathered(C_MAJOR, gathered).correct;
		});
		expect(results).toEqual([false, false, false, false, false, false, true]);
	});
});

describe('marking a passage', () => {
	const II_V_I = [
		[2, 5, 9, 0],
		[7, 11, 2, 5],
		[0, 4, 7, 11]
	];

	/** Play the chords in turn, the way the room does, and report where it ends. */
	const playThrough = (chords: number[][]) =>
		chords.reduce(
			(state, chord) => markPassage(II_V_I, state.done, chord),
			markPassage(II_V_I, 0, [])
		);

	it('accepts the chords played one after another', () => {
		const end = playThrough([
			[62, 65, 69, 72],
			[67, 71, 74, 77],
			[60, 64, 67, 71]
		]);
		expect(end.correct).toBe(true);
		expect(end.complete).toBe(true);
		expect(end.done).toBe(3);
	});

	/*
	 * The regression. Every note of all three chords together is what the page
	 * used to demand, and for this progression it is the entire major scale.
	 */
	it('refuses the whole progression played at once', () => {
		const union = [...new Set(II_V_I.flat())].map((pc) => 60 + pc);
		const marking = markPassage(II_V_I, 0, union);
		expect(marking.correct).toBe(false);
		expect(marking.complete).toBe(false);
		expect(marking.done).toBe(0);
	});

	it('advances one chord at a time and finishes on the last', () => {
		const played = [
			[62, 65, 69, 72],
			[67, 71, 74, 77],
			[60, 64, 67, 71]
		];
		let done = 0;
		const progress = played.map((chord) => {
			const marking = markPassage(II_V_I, done, chord);
			done = marking.done;
			return marking.complete;
		});
		expect(progress).toEqual([false, false, true]);
	});

	/*
	 * A wrong chord costs the attempt and nothing else. Sending somebody back to
	 * the top would make the movement — which is the whole exercise — impossible
	 * to practise.
	 */
	it('leaves a wrong chord where it found it', () => {
		const marking = markPassage(II_V_I, 1, [67, 71, 74]);
		expect(marking.correct).toBe(false);
		expect(marking.done).toBe(1);
		expect(marking.missing).toEqual([5]);
	});

	it('says what is missing from the chord being asked for, not from the rest', () => {
		const marking = markPassage(II_V_I, 0, [62, 65, 69]);
		expect(marking.missing).toEqual([0]);
		expect(marking.extra).toEqual([]);
	});

	it('marks each chord as a chord: octave and inversion free, extras not', () => {
		expect(markPassage(II_V_I, 0, [50, 53, 57, 60]).correct).toBe(true);
		expect(markPassage(II_V_I, 0, [62, 65, 69, 72, 74]).correct).toBe(true);
		expect(markPassage(II_V_I, 0, [62, 65, 69, 72, 73]).correct).toBe(false);
	});

	it('is not satisfied by silence', () => {
		expect(markPassage(II_V_I, 0, []).correct).toBe(false);
		expect(markPassage(II_V_I, 0, []).done).toBe(0);
	});

	it('stays finished once it is finished', () => {
		const past = markPassage(II_V_I, 3, [60, 64, 67, 71]);
		expect(past.complete).toBe(true);
		expect(past.done).toBe(3);
	});
});

describe('marking a named answer', () => {
	it('accepts the several ways of writing one chord', () => {
		for (const given of ['Cmaj7', 'CM7', 'C∆', 'cmaj7', ' Cmaj7 ']) {
			expect(markNamed('Cmaj7', given), given).toBe(true);
		}
	});

	it('accepts unicode accidentals', () => {
		expect(markNamed('Ebm7', 'E♭m7')).toBe(true);
		expect(markNamed('F#7', 'F♯7')).toBe(true);
	});

	it('accepts the half-diminished and diminished glyphs', () => {
		// ø carries its own seventh, so both spellings mean the same chord.
		expect(markNamed('Bm7b5', 'Bø7')).toBe(true);
		expect(markNamed('Bm7b5', 'Bø')).toBe(true);
		expect(markNamed('Bdim', 'B°')).toBe(true);
		expect(markNamed('Bdim7', 'B°7')).toBe(true);
	});

	it('handles an extension written after the triangle', () => {
		expect(markNamed('Cmaj9', 'C∆9')).toBe(true);
		expect(markNamed('Cmaj7', 'C∆7')).toBe(true);
	});

	it('accepts a dash for minor', () => {
		expect(markNamed('Dm7', 'D-7')).toBe(true);
	});

	it('rejects a different chord', () => {
		expect(markNamed('Cmaj7', 'C7')).toBe(false);
		expect(markNamed('Cmaj7', 'Cm7')).toBe(false);
		expect(markNamed('Cmaj7', 'Dmaj7')).toBe(false);
	});
});

describe('multiple choice', () => {
	const neighbours = ['Am7', 'C6', 'Em7', 'Cmaj9', 'Fmaj7'];

	it('always includes the right answer', () => {
		expect(choicesFor('Cmaj7', neighbours)).toContain('Cmaj7');
	});

	it('offers the requested number of options', () => {
		expect(choicesFor('Cmaj7', neighbours, 4)).toHaveLength(4);
		expect(choicesFor('Cmaj7', neighbours, 3)).toHaveLength(3);
	});

	it('draws the wrong answers from nearby chords, not at random', () => {
		// Guessing between four unrelated chords tests nothing.
		const options = choicesFor('Cmaj7', neighbours);
		for (const option of options) {
			if (option !== 'Cmaj7') expect(neighbours).toContain(option);
		}
	});

	it('never offers the same chord twice', () => {
		const options = choicesFor('Cmaj7', ['Cmaj7', 'C∆', 'Am7', 'Em7']);
		expect(new Set(options).size).toBe(options.length);
	});

	it('is stable, so resuming shows the same layout', () => {
		expect(choicesFor('Cmaj7', neighbours)).toEqual(choicesFor('Cmaj7', neighbours));
	});

	it('does not always put the answer first', () => {
		const positions = new Set(
			['Cmaj7', 'Dm7', 'G7', 'Am7', 'Fmaj7'].map((answer) =>
				choicesFor(answer, neighbours).indexOf(answer)
			)
		);
		expect(positions.size).toBeGreaterThan(1);
	});
});

describe('the wrong answers a naming question offers', () => {
	/*
	 * There were none. `hear_name` and the naming half of a degree had no control
	 * but "Reveal the name", which recorded a correct answer for being pressed —
	 * so the app's one number, the accuracy on the end screen, was partly a count
	 * of button presses. Four buttons is the smallest honest replacement, and they
	 * are only worth anything if the three wrong ones are confusable.
	 */
	const among = [
		{ label: 'Dm', kind: 'triad', keyCenter: 'C' },
		{ label: 'Em', kind: 'triad', keyCenter: 'C' },
		{ label: 'F', kind: 'triad', keyCenter: 'C' },
		{ label: 'D', kind: 'triad', keyCenter: 'G' },
		{ label: 'C', kind: 'triad', keyCenter: 'C' }
	];

	it('never offers the answer as one of the wrong ones', () => {
		expect(nameNeighbours('C', among, 'C')).not.toContain('C');
	});

	it('prefers chords from the key the question is in', () => {
		// The mistake runs along the key: a C major is confused with the other
		// chords of C, not with a D major from somewhere else.
		expect(nameNeighbours('C', among, 'C').slice(0, 3)).toEqual(['Dm', 'Em', 'F']);
	});

	it('still fills the buttons from elsewhere when the key is thin', () => {
		const thin = [
			{ label: 'Dm', kind: 'triad', keyCenter: 'C' },
			{ label: 'D', kind: 'triad', keyCenter: 'G' },
			{ label: 'A', kind: 'triad', keyCenter: 'G' }
		];
		expect(choicesFor('C', nameNeighbours('C', thin, 'C'))).toHaveLength(4);
	});

	it('does not offer the same name twice, however it is spelled', () => {
		const spellings = [
			{ label: 'Cmaj7', kind: 'seventh', keyCenter: 'C' },
			{ label: 'CM7', kind: 'seventh', keyCenter: 'C' },
			{ label: 'Dm7', kind: 'seventh', keyCenter: 'C' }
		];
		expect(nameNeighbours('C∆7', spellings, 'C')).toEqual(['Dm7']);
	});

	it('holds the right answer exactly once, wherever it lands', () => {
		const options = choicesFor('C', nameNeighbours('C', among, 'C'));
		expect(options.filter((option) => markNamed('C', option))).toHaveLength(1);
	});
});

describe('filling the buttons on an account that owns one chord', () => {
	/*
	 * The degenerate case, and it is the original bug wearing a different hat: two
	 * rungs up the bank holds exactly one triad, so wrong answers drawn only from
	 * the material leave a single button — press it, be right. The key the chord
	 * came from always has six more in it.
	 */
	it('offers the other six chords of the key', () => {
		// Spelled exactly as `ladder.ts` spells a card label — both go through
		// `formatChord`, so a derived name and a stored one are the same string and
		// `nameNeighbours` folds the duplicate away rather than offering it twice.
		expect(diatonicNames('C', 'triad').map((option) => option.label)).toEqual([
			'C',
			'Dm',
			'Em',
			'F',
			'G',
			'Am',
			'Bdim'
		]);
	});

	it('builds four choices from one card and the key around it', () => {
		const onlyCard = [{ label: 'C', kind: 'triad', keyCenter: 'C' }];
		const among = [...onlyCard, ...diatonicNames('C', 'triad')];
		const options = choicesFor('C', nameNeighbours('C', among, 'C'));
		expect(options).toHaveLength(4);
		expect(options.filter((option) => markNamed('C', option))).toHaveLength(1);
	});

	it('reads a mode label as the key it is in', () => {
		expect(diatonicNames('Eb mixolydian', 'triad')[0].label).toBe('Eb');
	});

	it('says nothing about a scale, which has no name to confuse', () => {
		expect(diatonicNames('C', 'scale')).toEqual([]);
	});

	it('says nothing about a key it cannot read', () => {
		expect(diatonicNames('not a key', 'triad')).toEqual([]);
	});
});

describe('the quality question', () => {
	const cards = (rungId: 'all-triads' | 'all-sevenths', key = 'C') =>
		cardsForRung(
			rungId,
			STAGES.find((s) => s.key === key)!
		).filter((card) => card.direction === 'hear_quality');

	it('sounds the chord and writes nothing down', () => {
		const [first] = cards('all-triads');
		const prompt = pose('hear_quality', first.payload, 60, 'C');
		expect(prompt.visible).toBeNull();
		expect(prompt.audible).not.toBeNull();
		expect(prompt.answerWith).toBe('quality');
	});

	it('refuses an anchor, because a quality is not counted from anywhere', () => {
		// The one aural question with no key in it. Sounding a tonic first would
		// suggest the key bears on an answer it cannot bear on.
		const [first] = cards('all-sevenths');
		expect(pose('hear_quality', first.payload, 60, 'C').anchor).toBeNull();
	});

	it('carries its answer on the card', () => {
		for (const rungId of ['all-triads', 'all-sevenths'] as const) {
			for (const card of cards(rungId)) {
				expect(card.payload.shape, card.payload.label).toBeTruthy();
			}
		}
	});

	it('names the sounds the triads rung actually teaches', () => {
		const shapes = new Set(cards('all-triads').map((card) => card.payload.shape));
		expect([...shapes].sort()).toEqual(['diminished', 'major', 'minor']);
	});

	it('names the four sevenths, which is the whole point of that rung', () => {
		const shapes = new Set(cards('all-sevenths').map((card) => card.payload.shape));
		expect([...shapes].sort()).toEqual([
			'dominant seventh',
			'half-diminished',
			'major seventh',
			'minor seventh'
		]);
	});

	it('offers every open shape, in teaching order, and never `unknown`', () => {
		const open: Shape[] = ['major', 'minor', 'diminished'];
		expect(shapeChoices('minor', open)).toEqual(['major', 'minor', 'diminished']);
		expect(shapeChoices('minor', [...open, 'unknown'])).not.toContain('unknown');
	});

	it('grows from three buttons to seven as the ladder opens', () => {
		const triads = vocabularyFromRungs(['scale', 'tonic-triad', 'all-triads']).shapes;
		const sevenths = vocabularyFromRungs(['all-triads', 'all-sevenths']).shapes;
		expect(shapeChoices('major', triads)).toHaveLength(3);
		expect(shapeChoices('major', sevenths)).toHaveLength(7);
	});

	it('never poses a card whose own answer is missing from the row', () => {
		// It cannot happen from `ensureLadderCards` — a card exists because its
		// rung is open — but a question you cannot answer is worth making
		// impossible rather than merely unlikely.
		expect(shapeChoices('dominant seventh', ['major', 'minor'])).toContain('dominant seventh');
	});

	it('marks only the shape the card is', () => {
		expect(markShape('minor seventh', 'minor seventh')).toBe(true);
		expect(markShape('minor seventh', 'half-diminished')).toBe(false);
		expect(markShape(undefined, 'major')).toBe(false);
	});
});

describe('the anchor under a naming question', () => {
	const namer = (key: string) =>
		cardsForRung(
			'all-sevenths',
			STAGES.find((s) => s.key === key)!
		).filter((card) => card.direction === 'hear_name')[0];

	it('sounds the tonic of the key before the chord', () => {
		// Without it, naming a chord sounded into silence is a test of perfect
		// pitch — and the ear queue crosses keys, so there was not even a stable
		// context to count from across a run.
		const prompt = pose('hear_name', namer('G').payload, 60, 'G');
		expect(prompt.anchor).toEqual([43]);
	});

	it('sounds one note and not the tonic chord, which on the I would be the answer', () => {
		// The fault a real morning printed: home came out as C–E–G and the chord
		// to be named came out as C–E–G an octave up, so the question answered
		// itself. One note leaves the shape above it still to be heard.
		const card = cardsForRung('all-triads', STAGES[0]).filter(
			(c) => c.direction === 'hear_name' && c.payload.label === 'C'
		)[0];
		const prompt = pose('hear_name', card.payload, 60, 'C');
		expect(prompt.anchor).toHaveLength(1);
		expect(new Set(prompt.audible!.map((n) => n % 12))).not.toEqual(
			new Set(prompt.anchor!.map((n) => n % 12))
		);
	});

	it('puts it below the chord, so it reads as ground rather than as part of it', () => {
		for (const key of ['C', 'G', 'F', 'Bb']) {
			const prompt = pose('hear_name', namer(key).payload, 60, key);
			expect(Math.max(...prompt.anchor!), key).toBeLessThan(Math.min(...prompt.audible!));
		}
	});

	it('puts the same key in the same place every time it is asked', () => {
		// Home should be the same note every question, not wherever the card's own
		// stored voicing happened to land.
		const anchors = cardsForRung('all-sevenths', STAGES[0])
			.filter((c) => c.direction === 'hear_name')
			.map((c) => pose('hear_name', c.payload, 60, 'C').anchor?.join());
		expect(new Set(anchors).size).toBe(1);
	});

	it('gives nothing rather than a guess when the key cannot be read', () => {
		expect(pose('hear_name', cmaj7, 60, 'not a key').anchor).toBeNull();
		expect(pose('hear_name', cmaj7, 60, undefined).anchor).toBeNull();
	});

	it('is never offered to a question answered with the hands', () => {
		for (const direction of ['see_play', 'hear_play', 'degree_play', 'pivot_play'] as const) {
			expect(pose(direction, cmaj7, 60, 'C').anchor, direction).toBeNull();
		}
	});
});

describe('wrong answers that vary the quality', () => {
	/** The bank an account three keys wide actually has, at the sevenths. */
	const bank = (kind: string) =>
		['C', 'G', 'F']
			.flatMap((key) =>
				cardsForRung(
					'all-sevenths',
					STAGES.find((s) => s.key === key)!
				)
			)
			.filter((card) => card.direction === 'hear_name' && card.payload.kind === kind)
			.map((card) => ({
				label: card.payload.label,
				kind: card.payload.kind,
				keyCenter: card.keyCenter
			}));

	it('puts the same root under a different quality first', () => {
		// The fault: G is the only G on the sevenths rung of C and B is the only
		// B, so the dominant and the half-diminished — the two most distinctive
		// sounds in the key — were the two you could get right by reading the
		// letter. `Gmaj7` and `Gm7` are real cards in G and F.
		const neighbours = nameNeighbours('G7', bank('seventh'), 'C');
		expect(neighbours.slice(0, 2).sort()).toEqual(['Gm7', 'Gmaj7']);
	});

	it('offers the half-diminished against the minor seventh it is confused with', () => {
		const options = choicesFor('Bm7b5', nameNeighbours('Bm7b5', bank('seventh'), 'C'));
		expect(options).toContain('Bm7');
	});

	it('still fills four buttons when no same-root option exists', () => {
		const onlyCard = [{ label: 'C', kind: 'triad', keyCenter: 'C' }];
		const among = [...onlyCard, ...diatonicNames('C', 'triad')];
		expect(choicesFor('C', nameNeighbours('C', among, 'C'))).toHaveLength(4);
	});

	it('reads a root through the accidental rather than around it', () => {
		// `Cm7b5` normalises to `cm7b5`, where the character after the letter is
		// `m` — so the root is `c` and not `cb`.
		const among = [
			{ label: 'Cm7b5', kind: 'seventh', keyCenter: 'Db' },
			{ label: 'Cbmaj7', kind: 'seventh', keyCenter: 'Gb' }
		];
		expect(nameNeighbours('Cmaj7', among, 'C')[0]).toBe('Cm7b5');
	});
});
