import {
	boolean,
	check,
	customType,
	index,
	integer,
	jsonb,
	pgEnum,
	pgTable,
	real,
	smallint,
	text,
	timestamp,
	unique,
	uniqueIndex,
	uuid
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import type { Landing } from '$lib/practice/match';
import type { Groove } from '$lib/audio/groove';
import type { TaskKind } from '$lib/session/workout';

/*
 * Conventions
 * -----------
 * Every primary key is a UUID generated by the *client*, not the database.
 * The practice session runs offline out of IndexedDB and flushes to Postgres
 * later, so rows must be creatable without a round trip and must merge
 * idempotently on replay. `defaultRandom()` is only a convenience for rows
 * created server-side (seeds, migrations).
 *
 * `key_center` is a text tonic spelling, never an integer: 'C', 'Eb', 'F#'.
 * Minor keys append 'm': 'Ebm'. Spelling is meaningful and must survive a
 * round trip through the database — see src/lib/music/spell.ts.
 *
 * Vocabularies the app will keep extending (block types, fact types, chart
 * styles, grooves) are `text` narrowed by a TypeScript union rather than a pgEnum,
 * because ALTER TYPE is a migration tax for no real benefit here. The three
 * vocabularies fixed by an algorithm — SRS card direction, FSRS state, FSRS
 * rating — are real enums.
 */

/** Raw captured MIDI. Postgres `bytea`, surfaced to TypeScript as a Uint8Array. */
const bytea = customType<{ data: Uint8Array; driverData: Buffer }>({
	dataType: () => 'bytea',
	toDriver: (value) => Buffer.from(value),
	fromDriver: (value) => new Uint8Array(value)
});

// ---------------------------------------------------------------------------
// Enums fixed by algorithm
// ---------------------------------------------------------------------------

/**
 * The directions from section 8, each named `stimulus_response`. Each is
 * scheduled independently because hearing, naming, playing and
 * reading-off-the-wheel are genuinely different skills — you can hear a chord
 * you cannot name.
 *
 * `key_hear`, `key_moved` and `pivot_play` are the sixth, seventh and eighth,
 * and they are the first directions whose subject is a *key* rather than a
 * chord. A cadence sounds and the answer is the note it came home to; two
 * cadences sound and the answer is where the second one landed; a chord is named
 * by its function in two keys at once and the answer is the chord. Between them
 * they are the questions this app could never ask, because every other direction
 * hands you the key in the prompt. Appended for the same reason `degree_play`
 * was, below.
 *
 * `degree_play` is the fifth and arrived last: the stimulus is a Roman numeral
 * and a key rather than a symbol, because seeing "A♭" and producing A♭ is
 * spelling while seeing "IV of E♭" and producing A♭ is harmony. It is appended
 * rather than filed next to `play_name` on purpose — `ALTER TYPE ... ADD VALUE`
 * only appends, so the order here has to be the order the type actually holds.
 */
export const cardDirection = pgEnum('card_direction', [
	'hear_name',
	'hear_play',
	'see_play',
	'play_name',
	'degree_play',
	'key_hear',
	'key_moved',
	'pivot_play'
]);

/** FSRS memory states. */
export const srsStateKind = pgEnum('srs_state_kind', ['new', 'learning', 'review', 'relearning']);

/** FSRS grades, 1–4. */
export const reviewRating = pgEnum('review_rating', ['again', 'hard', 'good', 'easy']);

// ---------------------------------------------------------------------------
// Narrowed text vocabularies
// ---------------------------------------------------------------------------

/**
 * A workout's task, as the row that records it names itself.
 *
 * The kind and the position, because neither alone identifies a task: a long
 * workout holds two missions, and `session_blocks` is keyed by session and type.
 * The position is what tells them apart; the kind is there so a row read on its
 * own still says what happened. The plan in `plan_json` stays the authority on
 * what task 2 actually was — this is how a block points at it.
 */
export type WorkoutBlockType = `${TaskKind}_${number}`;

/**
 * The six-block session's names for a block. **History, and not vocabulary.**
 *
 * Do not delete these, and do not write one. The distinction is the whole point
 * of the type existing on its own: M15 removed the six-block session, so nothing
 * in the app offers any of these any more — but `session_blocks` still holds the
 * rows, `practiceTotals` still counts the hours in them, and a row whose
 * `block_type` no type will admit is a row nobody can read back. The vocabulary
 * stopped; the record did not.
 *
 * `block_type` is text narrowed by a union rather than an enum precisely so this
 * could happen without a migration — the column was widened when workouts
 * arrived and nothing had to be rewritten, and nothing has to be rewritten now
 * that the older half is closed.
 */
export type LegacyBlockType =
	'wheel_warmup' | 'name_what_you_play' | 'ear_drill' | 'new_atom' | 'apply' | 'log';

/**
 * What a block of practice was: what can be written today, plus what was.
 *
 * This is the *reading* type, and the column carries it. The writing side is
 * narrower — `beginBlock` and `finishBlock` take a `WorkoutBlockType` and
 * nothing else — so the old names can still come back out of the database and
 * can no longer go into it.
 */
export type BlockType = WorkoutBlockType | LegacyBlockType;

export type SkillCategory =
	'inventory' | 'keys' | 'voicings' | 'progressions' | 'modes' | 'reharm' | 'application';

export type FactType =
	| 'key_used'
	| 'chord_quality_used'
	| 'inversion_used'
	| 'voicing_type_used'
	| 'top_note'
	| 'voice_leading_distance'
	| 'roman_numeral'
	| 'tempo'
	| 'voicing_diversity';

export type ChartStyle = 'blues' | 'minor_blues' | 'rhythm_changes' | 'modal_vamp' | 'custom';

/** What a rate-limited event was. Sign-in and reset requests share the table
 *  and are counted separately, so failing one never locks out the other. */
export type RateLimitKind = 'sign_in_failed' | 'reset_request';

// ---------------------------------------------------------------------------
// Tables
// ---------------------------------------------------------------------------

/**
 * One row per invited player. The original local player keeps its fixed id so
 * every existing foreign key and transitional cookie survives the migration.
 *
 * Everything owned cascades from here, designed in from this first migration
 * rather than discovered on the day somebody asks to be deleted.
 */
export const users = pgTable('users', {
	id: uuid('id').primaryKey(),
	name: text('name').notNull(),
	email: text('email').notNull().unique(),
	passwordHash: text('password_hash').notNull(),
	sessionEpoch: integer('session_epoch').notNull().default(0),
	createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
});

/**
 * A record of one failed sign-in or one reset request, kept only long enough
 * to be counted. No `user_id`: a failed sign-in has no account to blame it
 * on — the whole reason it needs limiting is that it might be aimed at
 * somebody else's — so the key is the normalised email being tried against,
 * the same value `authenticate` and `requestPasswordReset` already look up
 * by.
 *
 * One small table for both kinds, per ROADMAP.md's own reasoning: serverless
 * instances share no memory and Postgres is already there.
 */
export const rateLimitEvents = pgTable(
	'rate_limit_events',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		key: text('key').notNull(),
		kind: text('kind').$type<RateLimitKind>().notNull(),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [index('rate_limit_events_key_kind_created_idx').on(t.key, t.kind, t.createdAt)]
);

/**
 * A single-use password reset link, spent by `resetPassword`.
 *
 * `tokenHash` rather than the token itself — the raw value only ever exists
 * in the emailed link, the same discipline a session cookie's signature
 * already keeps: a leaked database row should not be a leaked credential.
 * `usedAt` rather than deleting the row on use, so a replayed link reads as
 * "already used" instead of "we have no idea what this was."
 */
export const passwordResetTokens = pgTable(
	'password_reset_tokens',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		userId: uuid('user_id')
			.notNull()
			.references(() => users.id, { onDelete: 'cascade' }),
		tokenHash: text('token_hash').notNull().unique(),
		expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
		usedAt: timestamp('used_at', { withTimezone: true }),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [index('password_reset_tokens_user_idx').on(t.userId)]
);

/**
 * Single row, id pinned to 1. This is the template copied into `user_prefs`
 * when an account is created. Existing installs keep their authored palette as
 * the template rather than silently returning to compiled defaults.
 */
export const settings = pgTable(
	'settings',
	{
		id: integer('id').primaryKey().default(1),
		colorMapJson: jsonb('color_map_json').notNull(),
		wheelConfigJson: jsonb('wheel_config_json').notNull(),
		midiDevice: text('midi_device'),
		prefsJson: jsonb('prefs_json').notNull(),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [check('settings_singleton', sql`${t.id} = 1`)]
);

/**
 * The settings that travel with one account.
 *
 * The singleton above is retained as the template for a newly provisioned
 * account. The first read copies that template here; every later read and write
 * is scoped by this primary key.
 */
export const userPrefs = pgTable('user_prefs', {
	userId: uuid('user_id')
		.primaryKey()
		.references(() => users.id, { onDelete: 'cascade' }),
	colorMapJson: jsonb('color_map_json').notNull(),
	wheelConfigJson: jsonb('wheel_config_json').notNull(),
	midiDevice: text('midi_device'),
	prefsJson: jsonb('prefs_json').notNull(),
	/**
	 * Whether the first-run tour has been seen. A fact about the account, not
	 * the browser — it was `localStorage`, keyed by name, until M12 gave every
	 * account somewhere of its own to keep it. No default from the singleton
	 * template: a new account has always seen nothing, whatever the operator's
	 * own row says.
	 */
	tourSeen: boolean('tour_seen').notNull().default(false),
	updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
});

/** The curriculum DAG from section 7. Seeded, never authored at runtime. */
export const skills = pgTable(
	'skills',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		code: text('code').notNull().unique(),
		name: text('name').notNull(),
		level: smallint('level').notNull(),
		category: text('category').$type<SkillCategory>().notNull(),
		description: text('description').notNull(),
		/** Array of skill *codes*, not UUIDs — stable across reseeds and readable. */
		prereqIdsJson: jsonb('prereq_ids_json').$type<string[]>().notNull().default([]),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [index('skills_level_idx').on(t.level)]
);

/** Cards are generated from (skill, key, instance, direction), never authored. */
export const cards = pgTable(
	'cards',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		userId: uuid('user_id')
			.notNull()
			.references(() => users.id, { onDelete: 'cascade' }),
		skillId: uuid('skill_id')
			.notNull()
			.references(() => skills.id, { onDelete: 'cascade' }),
		direction: cardDirection('direction').notNull(),
		keyCenter: text('key_center').notNull(),
		payloadJson: jsonb('payload_json').notNull(),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [
		index('cards_user_idx').on(t.userId),
		index('cards_skill_idx').on(t.skillId),
		index('cards_key_idx').on(t.keyCenter)
	]
);

/** FSRS scheduling state, one row per card. */
export const srsState = pgTable(
	'srs_state',
	{
		cardId: uuid('card_id')
			.primaryKey()
			.references(() => cards.id, { onDelete: 'cascade' }),
		stability: real('stability').notNull(),
		difficulty: real('difficulty').notNull(),
		dueAt: timestamp('due_at', { withTimezone: true }).notNull(),
		reps: integer('reps').notNull().default(0),
		lapses: integer('lapses').notNull().default(0),
		state: srsStateKind('state').notNull().default('new'),
		lastReviewedAt: timestamp('last_reviewed_at', { withTimezone: true })
	},
	(t) => [index('srs_due_idx').on(t.dueAt)]
);

export const sessions = pgTable(
	'sessions',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		userId: uuid('user_id')
			.notNull()
			.references(() => users.id, { onDelete: 'cascade' }),
		startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
		endedAt: timestamp('ended_at', { withTimezone: true }),
		keyCenter: text('key_center').notNull(),
		planJson: jsonb('plan_json').notNull(),
		resultJson: jsonb('result_json'),
		notes: text('notes')
	},
	(t) => [index('sessions_user_started_idx').on(t.userId, t.startedAt)]
);

export const sessionBlocks = pgTable(
	'session_blocks',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		sessionId: uuid('session_id')
			.notNull()
			.references(() => sessions.id, { onDelete: 'cascade' }),
		blockType: text('block_type').$type<BlockType>().notNull(),
		startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
		endedAt: timestamp('ended_at', { withTimezone: true }),
		resultJson: jsonb('result_json')
	},
	(t) => [index('session_blocks_session_idx').on(t.sessionId)]
);

/**
 * Append-only. `latencyMs` is the time from stimulus to correct answer and is
 * the single best proxy for fluency, so it is a first-class column rather than
 * something buried in a JSON payload.
 */
export const reviews = pgTable(
	'reviews',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		cardId: uuid('card_id')
			.notNull()
			.references(() => cards.id, { onDelete: 'cascade' }),
		sessionId: uuid('session_id').references(() => sessions.id, { onDelete: 'set null' }),
		ts: timestamp('ts', { withTimezone: true }).notNull().defaultNow(),
		rating: reviewRating('rating').notNull(),
		correct: boolean('correct').notNull(),
		latencyMs: integer('latency_ms'),
		playedJson: jsonb('played_json')
	},
	(t) => [
		index('reviews_card_idx').on(t.cardId),
		index('reviews_session_idx').on(t.sessionId),
		index('reviews_ts_idx').on(t.ts)
	]
);

/**
 * Raw captured MIDI kept forever and re-analysable later: the analysis engine
 * will improve, and old takes should benefit retroactively. That is why the
 * blob is stored alongside `analysisJson` rather than instead of it.
 *
 * `userId` is direct rather than reached through `sessionId`, and that is the
 * fix M12 made to this table rather than the shape it shipped in: a take's
 * session link is nullable and `set null`, which is right for a take outliving
 * a deleted session but meant a take had no *reliable* path back to a user at
 * all — the one thing an owned table cannot be missing once deleting an
 * account has to actually work. Still parked, still nothing writes to it; the
 * column is here so that when something does, it is owned from the first row.
 */
export const takes = pgTable(
	'takes',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		userId: uuid('user_id')
			.notNull()
			.references(() => users.id, { onDelete: 'cascade' }),
		sessionId: uuid('session_id').references(() => sessions.id, { onDelete: 'set null' }),
		ts: timestamp('ts', { withTimezone: true }).notNull().defaultNow(),
		midiBlob: bytea('midi_blob').notNull(),
		bpm: real('bpm'),
		durationMs: integer('duration_ms').notNull(),
		analysisJson: jsonb('analysis_json'),
		tags: text('tags')
			.array()
			.notNull()
			.default(sql`ARRAY[]::text[]`)
	},
	(t) => [
		index('takes_user_idx').on(t.userId),
		index('takes_session_idx').on(t.sessionId),
		index('takes_ts_idx').on(t.ts)
	]
);

/**
 * Named progressions, whether captured from playing or imported as a chart.
 *
 * `userId` direct, for the same reason `takes` now carries one: `sourceTakeId`
 * is nullable and `set null`, so a repertoire entry had no owner a cascading
 * delete could find even after `takes` was fixed — the gap doubled rather than
 * moved. Still parked, still nothing writes to it.
 */
export const repertoire = pgTable(
	'repertoire',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		userId: uuid('user_id')
			.notNull()
			.references(() => users.id, { onDelete: 'cascade' }),
		name: text('name').notNull(),
		sourceTakeId: uuid('source_take_id').references(() => takes.id, { onDelete: 'set null' }),
		chartJson: jsonb('chart_json'),
		keyCenter: text('key_center').notNull(),
		romanJson: jsonb('roman_json'),
		notes: text('notes'),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [index('repertoire_user_idx').on(t.userId)]
);

/**
 * Flattened facts extracted from a take, one row per observation. Kept narrow
 * and long rather than wide so the blind-spot report is a GROUP BY instead of
 * a schema migration every time a new dimension is worth tracking.
 */
export const analysisFacts = pgTable(
	'analysis_facts',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		takeId: uuid('take_id')
			.notNull()
			.references(() => takes.id, { onDelete: 'cascade' }),
		factType: text('fact_type').$type<FactType>().notNull(),
		factKey: text('fact_key').notNull(),
		valueNum: real('value_num'),
		valueText: text('value_text')
	},
	(t) => [
		index('analysis_facts_take_idx').on(t.takeId),
		index('analysis_facts_type_key_idx').on(t.factType, t.factKey)
	]
);

/**
 * The app's real scoreboard: a skill learned in a lesson turning up unprompted
 * in a later free-play take.
 */
export const transferEvents = pgTable(
	'transfer_events',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		skillId: uuid('skill_id')
			.notNull()
			.references(() => skills.id, { onDelete: 'cascade' }),
		takeId: uuid('take_id')
			.notNull()
			.references(() => takes.id, { onDelete: 'cascade' }),
		ts: timestamp('ts', { withTimezone: true }).notNull().defaultNow(),
		evidenceJson: jsonb('evidence_json').notNull()
	},
	(t) => [
		index('transfer_events_skill_idx').on(t.skillId),
		index('transfer_events_take_idx').on(t.takeId)
	]
);

/**
 * Chord charts as data — a grid of chord symbols, never notation.
 *
 * `slug`, `mode` and `notes` were buried in `grid_json` and are columns now.
 * The slug is how a chart is addressed in a URL and how the built-in ones are
 * told apart from yours, which meant every page load read every row and
 * filtered them in application code to find a value the database could not see.
 *
 * `grid_json` keeps the grid and nothing else: rows of bars, each bar a string
 * of Roman numerals. It stays JSON because it is a nested array nothing queries
 * into — the one shape here that genuinely is a document.
 *
 * `user_id` is the one nullable owner in the schema, and the null means
 * something: **null is built-in and shared, a value is yours.** `db:seed` writes
 * the forms, cycles and standards into this table from `charts.ts`, so a NOT
 * NULL backfill would have handed the shared repertoire to whoever happened to
 * be the first row in `users`. The list on the play-along page is the union of
 * the two, which is what it already showed.
 */
export const charts = pgTable(
	'charts',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		userId: uuid('user_id').references(() => users.id, { onDelete: 'cascade' }),
		slug: text('slug').notNull(),
		name: text('name').notNull(),
		gridJson: jsonb('grid_json').$type<string[][]>().notNull(),
		style: text('style').$type<ChartStyle>().notNull(),
		mode: text('mode').$type<'major' | 'minor'>().notNull().default('major'),
		/** What the tune is *for* practising, in the voice the built-ins use. */
		notes: text('notes').notNull().default(''),
		defaultBpm: integer('default_bpm').notNull(),
		/**
		 * How the tune opens: the rhythm section it wants, and the key it is in.
		 *
		 * A form has no key — a twelve-bar blues is a twelve-bar blues in all
		 * twelve — so `default_key` is null for every built-in, and that null is a
		 * claim rather than a missing value. A song does have one, and it is the key
		 * you wrote the chart down in, which is why the editor stores what it
		 * already asked for instead of asking twice.
		 *
		 * `default_groove` is `text` narrowed by a union for the reason given at the
		 * top of this file: grooves are a vocabulary that will keep being added to,
		 * and adding one should not be a migration.
		 */
		defaultGroove: text('default_groove').$type<Groove>().notNull().default('swing'),
		defaultKey: text('default_key'),
		/**
		 * The words, in the same shape as `grid_json`: rows of bars, one fragment
		 * per bar. Null for an instrumental, and the null is load-bearing — every
		 * screen that would draw lyrics checks it and draws nothing, so a chart
		 * without words looks exactly as it did before words existed.
		 *
		 * JSON for the same reason the grid is: it is a nested array nothing
		 * queries into, and it is the one other genuinely document-shaped thing
		 * here. Kept beside the grid rather than in it so that an instrumental
		 * costs a null and not a parallel array of empty strings.
		 */
		lyricsJson: jsonb('lyrics_json').$type<string[][]>(),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [
		index('charts_slug_idx').on(t.slug),
		uniqueIndex('charts_user_slug_unique').on(t.userId, t.slug),
		uniqueIndex('charts_shared_slug_unique')
			.on(t.slug)
			.where(sql`${t.userId} is null`)
	]
);

/**
 * One row per run of the transport: play pressed to stop pressed.
 *
 * The `Tally` is flattened into columns rather than kept as `jsonb` because the
 * profile sums it on every load and it is a closed vocabulary — seven numbers,
 * unchanged since the day scoring shipped. `analysis_facts` is narrow and long
 * for the opposite reason: its dimensions keep being added to.
 *
 * `chart_slug` rather than a foreign key, because the built-in charts live in
 * code and have no row to point at. `chart_id` is set only for a chart of your
 * own, and survives that chart being deleted — the run still happened, and the
 * slug still says what it was played over.
 *
 * `best_streak` is why the streak record no longer stores a best at all: a
 * streak cannot outlive the transport, so the best ever is `MAX(best_streak)`
 * here and the best on a tune is the same grouped by slug. Nothing left to
 * reconcile, because there is only one place the answer comes from.
 */
export const playRuns = pgTable(
	'play_runs',
	{
		id: uuid('id').primaryKey(),
		userId: uuid('user_id')
			.notNull()
			.references(() => users.id, { onDelete: 'cascade' }),
		chartSlug: text('chart_slug').notNull(),
		chartId: uuid('chart_id').references(() => charts.id, { onDelete: 'set null' }),
		/**
		 * The mission block this run answered, or null for a free run — which stays
		 * the common case, because playing along belongs to no session.
		 *
		 * It is what makes a goal's verdict traceable: the block holds the verdict,
		 * this points at the run that earned it, and `chord_attempts` holds every
		 * chord the run was judged on. `set null` rather than `cascade`, following
		 * the same reasoning as `chart_id` above — deleting a session must not
		 * delete an hour of playing.
		 */
		sessionBlockId: uuid('session_block_id').references(() => sessionBlocks.id, {
			onDelete: 'set null'
		}),
		keyCenter: text('key_center').notNull(),
		bpm: integer('bpm').notNull(),
		/** The groove it was played over. Called `feel` until grooves existed, when
		 * a column holding 'rock' would have been a column lying about its name. */
		groove: text('groove').notNull(),
		startedAt: timestamp('started_at', { withTimezone: true }).notNull(),
		endedAt: timestamp('ended_at', { withTimezone: true }),
		/** Transport running and not paused, count-in included. Never page-open time. */
		playingMs: integer('playing_ms').notNull(),
		voiced: integer('voiced').notNull(),
		landed: integer('landed').notNull(),
		partial: integer('partial').notNull(),
		missed: integer('missed').notNull(),
		notesChord: integer('notes_chord').notNull(),
		notesColour: integer('notes_colour').notNull(),
		notesOutside: integer('notes_outside').notNull(),
		bestStreak: integer('best_streak').notNull(),
		/**
		 * The tempo the best streak was clinched at, or null when it was not
		 * witnessed.
		 *
		 * Tempo moves under a running transport by design, so `bpm` above is the
		 * tempo the run *ended* at and says nothing about where a streak was
		 * reached: a run started at 140 and slowed to 60 records one number, and if
		 * the streak was clinched after the slowdown the record flatters. This is a
		 * fact about the run rather than a copy of an aggregate — the tempo showing
		 * at the moment `best` was last raised — so it does not reopen the argument
		 * that deleted the stored best.
		 *
		 * **It cannot be backfilled.** The runs already logged do not know, and
		 * inventing a number for them would be the first estimate in a record that
		 * has never held one. Nothing reads it yet; it is captured now because every
		 * day it does not exist is a day of history that can never be graded
		 * honestly.
		 */
		bestStreakBpm: integer('best_streak_bpm')
	},
	(t) => [
		index('play_runs_user_started_idx').on(t.userId, t.startedAt),
		index('play_runs_user_chart_idx').on(t.userId, t.chartSlug)
	]
);

/**
 * One row per judged chord. A few thousand for an hour of playing, kept.
 *
 * This is the grain the blind-spot report needs and it cannot be reconstructed
 * after the fact, which is the whole argument for writing it down rather than
 * only the totals it rolls up into.
 *
 * No `user_id`. It cannot exist without its run and the run has one; the same
 * fact stored twice is a fact able to disagree with itself. The cost is a join
 * on every profile query and it is worth it.
 */
export const chordAttempts = pgTable(
	'chord_attempts',
	{
		id: uuid('id').primaryKey(),
		runId: uuid('run_id')
			.notNull()
			.references(() => playRuns.id, { onDelete: 'cascade' }),
		/** Bar of the form, not of the loop. */
		bar: integer('bar').notNull(),
		/** As it sounded, in the key it was played in. */
		chord: text('chord').notNull(),
		/** As the chart stores it. */
		numeral: text('numeral').notNull(),
		/** The key it was heard in, from `studyProgression` — not the tune's home key. */
		localKey: text('local_key').notNull(),
		landing: text('landing').$type<Landing>().notNull(),
		found: smallint('found').notNull(),
		needed: smallint('needed').notNull(),
		notesChord: smallint('notes_chord').notNull(),
		notesColour: smallint('notes_colour').notNull(),
		notesOutside: smallint('notes_outside').notNull(),
		/** Offset into the run, on the run's own clock. */
		atMs: integer('at_ms').notNull()
	},
	(t) => [index('chord_attempts_run_idx').on(t.runId)]
);

/**
 * The shelf. A badge is a milestone; a run is telemetry.
 *
 * Different lifetimes, so a table of its own rather than a `GROUP BY` over the
 * log — if the log is ever pruned the shelf has to survive it.
 *
 * The unique constraint is the first-earned-wins rule moved out of TypeScript
 * and into the schema, so `insert … on conflict do nothing` is now the whole of
 * it. Keyed per chart, which is what makes a badge worth more than it was:
 * fifty in a row *on this tune* is three clean passes of that form, where fifty
 * in a row on whatever happened to be playing was an afternoon.
 */
export const badges = pgTable(
	'badges',
	{
		id: uuid('id').primaryKey(),
		userId: uuid('user_id')
			.notNull()
			.references(() => users.id, { onDelete: 'cascade' }),
		chartSlug: text('chart_slug').notNull(),
		/** The tier's stable id, never its name: a rename must not orphan a badge. */
		tier: text('tier').notNull(),
		wonAt: timestamp('won_at', { withTimezone: true }).notNull(),
		/** The streak that clinched it, which may be higher than the tier's threshold. */
		count: integer('count').notNull(),
		/** Pitch class of the clinching chord. The badge's colour. */
		pc: smallint('pc').notNull(),
		keyCenter: text('key_center').notNull(),
		runId: uuid('run_id').references(() => playRuns.id, { onDelete: 'set null' })
	},
	(t) => [
		unique('badges_user_chart_tier').on(t.userId, t.chartSlug, t.tier),
		index('badges_user_idx').on(t.userId)
	]
);

// ---------------------------------------------------------------------------
// Inferred types
// ---------------------------------------------------------------------------

export type Settings = typeof settings.$inferSelect;
export type Skill = typeof skills.$inferSelect;
export type Card = typeof cards.$inferSelect;
export type SrsState = typeof srsState.$inferSelect;
export type Session = typeof sessions.$inferSelect;
export type SessionBlock = typeof sessionBlocks.$inferSelect;
export type Review = typeof reviews.$inferSelect;
export type Take = typeof takes.$inferSelect;
export type RepertoireEntry = typeof repertoire.$inferSelect;
export type AnalysisFact = typeof analysisFacts.$inferSelect;
export type TransferEvent = typeof transferEvents.$inferSelect;
export type Chart = typeof charts.$inferSelect;
export type User = typeof users.$inferSelect;
export type PlayRun = typeof playRuns.$inferSelect;
export type ChordAttempt = typeof chordAttempts.$inferSelect;
export type BadgeRow = typeof badges.$inferSelect;
export type RateLimitEvent = typeof rateLimitEvents.$inferSelect;
export type PasswordResetToken = typeof passwordResetTokens.$inferSelect;

export type CardDirection = (typeof cardDirection.enumValues)[number];
export type SrsStateKind = (typeof srsStateKind.enumValues)[number];
export type ReviewRating = (typeof reviewRating.enumValues)[number];
