import {
	boolean,
	check,
	customType,
	index,
	integer,
	jsonb,
	pgEnum,
	pgTable,
	real,
	smallint,
	text,
	timestamp,
	uuid
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

/*
 * Conventions
 * -----------
 * Every primary key is a UUID generated by the *client*, not the database.
 * The practice session runs offline out of IndexedDB and flushes to Postgres
 * later, so rows must be creatable without a round trip and must merge
 * idempotently on replay. `defaultRandom()` is only a convenience for rows
 * created server-side (seeds, migrations).
 *
 * `key_center` is a text tonic spelling, never an integer: 'C', 'Eb', 'F#'.
 * Minor keys append 'm': 'Ebm'. Spelling is meaningful and must survive a
 * round trip through the database — see src/lib/music/spell.ts.
 *
 * Vocabularies the app will keep extending (block types, fact types, chart
 * styles) are `text` narrowed by a TypeScript union rather than a pgEnum,
 * because ALTER TYPE is a migration tax for no real benefit here. The three
 * vocabularies fixed by an algorithm — SRS card direction, FSRS state, FSRS
 * rating — are real enums.
 */

/** Raw captured MIDI. Postgres `bytea`, surfaced to TypeScript as a Uint8Array. */
const bytea = customType<{ data: Uint8Array; driverData: Buffer }>({
	dataType: () => 'bytea',
	toDriver: (value) => Buffer.from(value),
	fromDriver: (value) => new Uint8Array(value)
});

// ---------------------------------------------------------------------------
// Enums fixed by algorithm
// ---------------------------------------------------------------------------

/**
 * The four directions from section 8. Each is scheduled independently because
 * hearing, naming, playing and reading-off-the-wheel are genuinely different
 * skills — you can hear a chord you cannot name.
 */
export const cardDirection = pgEnum('card_direction', [
	'hear_name',
	'hear_play',
	'see_play',
	'play_name'
]);

/** FSRS memory states. */
export const srsStateKind = pgEnum('srs_state_kind', ['new', 'learning', 'review', 'relearning']);

/** FSRS grades, 1–4. */
export const reviewRating = pgEnum('review_rating', ['again', 'hard', 'good', 'easy']);

// ---------------------------------------------------------------------------
// Narrowed text vocabularies
// ---------------------------------------------------------------------------

export type BlockType =
	'wheel_warmup' | 'name_what_you_play' | 'ear_drill' | 'new_atom' | 'apply' | 'log';

export type SkillCategory =
	'inventory' | 'keys' | 'voicings' | 'progressions' | 'modes' | 'reharm' | 'application';

export type FactType =
	| 'key_used'
	| 'chord_quality_used'
	| 'inversion_used'
	| 'voicing_type_used'
	| 'top_note'
	| 'voice_leading_distance'
	| 'roman_numeral'
	| 'tempo'
	| 'voicing_diversity';

export type ChartStyle = 'blues' | 'minor_blues' | 'rhythm_changes' | 'modal_vamp' | 'custom';

// ---------------------------------------------------------------------------
// Tables
// ---------------------------------------------------------------------------

/**
 * Single row, id pinned to 1. Holds the editable design tokens (the twelve
 * pitch-class colours) and the harmonic wheel calibration, both of which the
 * brief requires to live in the database rather than in CSS so they can be
 * matched to a physical wheel or coloured stickers on the keys.
 */
export const settings = pgTable(
	'settings',
	{
		id: integer('id').primaryKey().default(1),
		colorMapJson: jsonb('color_map_json').notNull(),
		wheelConfigJson: jsonb('wheel_config_json').notNull(),
		midiDevice: text('midi_device'),
		prefsJson: jsonb('prefs_json').notNull(),
		updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [check('settings_singleton', sql`${t.id} = 1`)]
);

/** The curriculum DAG from section 7. Seeded, never authored at runtime. */
export const skills = pgTable(
	'skills',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		code: text('code').notNull().unique(),
		name: text('name').notNull(),
		level: smallint('level').notNull(),
		category: text('category').$type<SkillCategory>().notNull(),
		description: text('description').notNull(),
		/** Array of skill *codes*, not UUIDs — stable across reseeds and readable. */
		prereqIdsJson: jsonb('prereq_ids_json').$type<string[]>().notNull().default([]),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [index('skills_level_idx').on(t.level)]
);

/** Cards are generated from (skill, key, instance, direction), never authored. */
export const cards = pgTable(
	'cards',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		skillId: uuid('skill_id')
			.notNull()
			.references(() => skills.id, { onDelete: 'cascade' }),
		direction: cardDirection('direction').notNull(),
		keyCenter: text('key_center').notNull(),
		payloadJson: jsonb('payload_json').notNull(),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [index('cards_skill_idx').on(t.skillId), index('cards_key_idx').on(t.keyCenter)]
);

/** FSRS scheduling state, one row per card. */
export const srsState = pgTable(
	'srs_state',
	{
		cardId: uuid('card_id')
			.primaryKey()
			.references(() => cards.id, { onDelete: 'cascade' }),
		stability: real('stability').notNull(),
		difficulty: real('difficulty').notNull(),
		dueAt: timestamp('due_at', { withTimezone: true }).notNull(),
		reps: integer('reps').notNull().default(0),
		lapses: integer('lapses').notNull().default(0),
		state: srsStateKind('state').notNull().default('new'),
		lastReviewedAt: timestamp('last_reviewed_at', { withTimezone: true })
	},
	(t) => [index('srs_due_idx').on(t.dueAt)]
);

export const sessions = pgTable('sessions', {
	id: uuid('id').primaryKey().defaultRandom(),
	startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
	endedAt: timestamp('ended_at', { withTimezone: true }),
	keyCenter: text('key_center').notNull(),
	planJson: jsonb('plan_json').notNull(),
	resultJson: jsonb('result_json'),
	notes: text('notes')
});

export const sessionBlocks = pgTable(
	'session_blocks',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		sessionId: uuid('session_id')
			.notNull()
			.references(() => sessions.id, { onDelete: 'cascade' }),
		blockType: text('block_type').$type<BlockType>().notNull(),
		startedAt: timestamp('started_at', { withTimezone: true }).notNull().defaultNow(),
		endedAt: timestamp('ended_at', { withTimezone: true }),
		resultJson: jsonb('result_json')
	},
	(t) => [index('session_blocks_session_idx').on(t.sessionId)]
);

/**
 * Append-only. `latencyMs` is the time from stimulus to correct answer and is
 * the single best proxy for fluency, so it is a first-class column rather than
 * something buried in a JSON payload.
 */
export const reviews = pgTable(
	'reviews',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		cardId: uuid('card_id')
			.notNull()
			.references(() => cards.id, { onDelete: 'cascade' }),
		sessionId: uuid('session_id').references(() => sessions.id, { onDelete: 'set null' }),
		ts: timestamp('ts', { withTimezone: true }).notNull().defaultNow(),
		rating: reviewRating('rating').notNull(),
		correct: boolean('correct').notNull(),
		latencyMs: integer('latency_ms'),
		playedJson: jsonb('played_json')
	},
	(t) => [
		index('reviews_card_idx').on(t.cardId),
		index('reviews_session_idx').on(t.sessionId),
		index('reviews_ts_idx').on(t.ts)
	]
);

/**
 * Raw captured MIDI kept forever and re-analysable later: the analysis engine
 * will improve, and old takes should benefit retroactively. That is why the
 * blob is stored alongside `analysisJson` rather than instead of it.
 */
export const takes = pgTable(
	'takes',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		sessionId: uuid('session_id').references(() => sessions.id, { onDelete: 'set null' }),
		ts: timestamp('ts', { withTimezone: true }).notNull().defaultNow(),
		midiBlob: bytea('midi_blob').notNull(),
		bpm: real('bpm'),
		durationMs: integer('duration_ms').notNull(),
		analysisJson: jsonb('analysis_json'),
		tags: text('tags')
			.array()
			.notNull()
			.default(sql`ARRAY[]::text[]`)
	},
	(t) => [index('takes_session_idx').on(t.sessionId), index('takes_ts_idx').on(t.ts)]
);

/** Named progressions, whether captured from playing or imported as a chart. */
export const repertoire = pgTable('repertoire', {
	id: uuid('id').primaryKey().defaultRandom(),
	name: text('name').notNull(),
	sourceTakeId: uuid('source_take_id').references(() => takes.id, { onDelete: 'set null' }),
	chartJson: jsonb('chart_json'),
	keyCenter: text('key_center').notNull(),
	romanJson: jsonb('roman_json'),
	notes: text('notes'),
	createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
});

/**
 * Flattened facts extracted from a take, one row per observation. Kept narrow
 * and long rather than wide so the blind-spot report is a GROUP BY instead of
 * a schema migration every time a new dimension is worth tracking.
 */
export const analysisFacts = pgTable(
	'analysis_facts',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		takeId: uuid('take_id')
			.notNull()
			.references(() => takes.id, { onDelete: 'cascade' }),
		factType: text('fact_type').$type<FactType>().notNull(),
		factKey: text('fact_key').notNull(),
		valueNum: real('value_num'),
		valueText: text('value_text')
	},
	(t) => [
		index('analysis_facts_take_idx').on(t.takeId),
		index('analysis_facts_type_key_idx').on(t.factType, t.factKey)
	]
);

/**
 * The app's real scoreboard: a skill learned in a lesson turning up unprompted
 * in a later free-play take.
 */
export const transferEvents = pgTable(
	'transfer_events',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		skillId: uuid('skill_id')
			.notNull()
			.references(() => skills.id, { onDelete: 'cascade' }),
		takeId: uuid('take_id')
			.notNull()
			.references(() => takes.id, { onDelete: 'cascade' }),
		ts: timestamp('ts', { withTimezone: true }).notNull().defaultNow(),
		evidenceJson: jsonb('evidence_json').notNull()
	},
	(t) => [
		index('transfer_events_skill_idx').on(t.skillId),
		index('transfer_events_take_idx').on(t.takeId)
	]
);

/**
 * Chord charts as data — a grid of chord symbols, never notation.
 *
 * `slug`, `mode` and `notes` were buried in `grid_json` and are columns now.
 * The slug is how a chart is addressed in a URL and how the built-in ones are
 * told apart from yours, which meant every page load read every row and
 * filtered them in application code to find a value the database could not see.
 *
 * `grid_json` keeps the grid and nothing else: rows of bars, each bar a string
 * of Roman numerals. It stays JSON because it is a nested array nothing queries
 * into — the one shape here that genuinely is a document.
 *
 * No `user_id` yet. It belongs here and is deliberately left to M9, which
 * creates the `users` table and the accessor every owned query goes through;
 * adding the column first would mean inventing half of that seam early.
 */
export const charts = pgTable(
	'charts',
	{
		id: uuid('id').primaryKey().defaultRandom(),
		slug: text('slug').notNull().unique(),
		name: text('name').notNull(),
		gridJson: jsonb('grid_json').$type<string[][]>().notNull(),
		style: text('style').$type<ChartStyle>().notNull(),
		mode: text('mode').$type<'major' | 'minor'>().notNull().default('major'),
		/** What the tune is *for* practising, in the voice the built-ins use. */
		notes: text('notes').notNull().default(''),
		defaultBpm: integer('default_bpm').notNull(),
		createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow()
	},
	(t) => [index('charts_slug_idx').on(t.slug)]
);

// ---------------------------------------------------------------------------
// Inferred types
// ---------------------------------------------------------------------------

export type Settings = typeof settings.$inferSelect;
export type Skill = typeof skills.$inferSelect;
export type Card = typeof cards.$inferSelect;
export type SrsState = typeof srsState.$inferSelect;
export type Session = typeof sessions.$inferSelect;
export type SessionBlock = typeof sessionBlocks.$inferSelect;
export type Review = typeof reviews.$inferSelect;
export type Take = typeof takes.$inferSelect;
export type RepertoireEntry = typeof repertoire.$inferSelect;
export type AnalysisFact = typeof analysisFacts.$inferSelect;
export type TransferEvent = typeof transferEvents.$inferSelect;
export type Chart = typeof charts.$inferSelect;

export type CardDirection = (typeof cardDirection.enumValues)[number];
export type SrsStateKind = (typeof srsStateKind.enumValues)[number];
export type ReviewRating = (typeof reviewRating.enumValues)[number];
